### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by Trblz42** [jimmyjon711/FactorioExtended-Plus-Machines#14]
Mods to disable:Failed to load mods: Error while running setup for entity prototype "electric-mining-drill" (mining-drill): next_upgrade target (Schall-uranium-mining-drill) must have the same fast_replaceable_group (mining-drill != electric-mining-drill).

Mods to be disabled:
• FactorioExtended-Plus-Machines
• SchallAlienTech

Running FE+ in combination  with Schall mods AlienTech and weapons

Related issue with Schallfalke on the mods portal: https://mods.factorio.com/mod/SchallAlienTech/discussion/5e3b8e49da6d8f000b0977b3

**Comment by billbo99** [comment]
When the next code is released,  if there is an existing "facst_replace_group" we will use it,  otherwise one will need to be set so that entities can be upgraded from mk1->mk2->mk3

**Comment by jimmyjon711** [comment]
I am going to close this issue, if you are still having a problem with this please let us know.

**Comment by Trblz42** [comment]
Loading problem solved. I will test it more during this long weekend

thanks
