### ISSUE TITLE
ratios are off

### ISSUE THREAD

**Issue by DeadlyKitten37** [jimmyjon711/FactorioExtended-Plus-Machines#16]
the crafting speeds for the chem plant goes 1 -> 2.5 -> 5 instead of a normal doubling (1 -> 2 -> 4) as I believe is intended, this is due to the update from 16 to 17 changing the speed from 1.25 to 1 and was previously fixed by another mod that is not being updated

**Comment by billbo99** [comment]
Noted, PR raised to fix the ratio.
