### ISSUE TITLE
mod compatibility

### ISSUE THREAD

**Issue by DeadlyKitten37** [jimmyjon711/FactorioExtended-Plus-Machines#18]
mod compatibility issue with Production Scrap 2, (https://mods.factorio.com/mod/ProductionScrap2/). this mod creates scrap side products for vanilla recipes, the scrap for iron, copper, or steel plate does not exist when smelted in FE electric furnaces, no such issue appears in my testing with higher tier assemblers.

PS issue on other mods page is here -https://mods.factorio.com/mod/ProductionScrap2/discussion/5e51259c9ddac0000b6c2339

**Comment by billbo99** [comment]
This looks to be something that needs to be coded on the "ProductionScrap2" side.   In the file "data-updates.lua" I can see the author has added compatibility for a few mods that add furnaces; eg  "DoubleFurnace" / "Electric Furnaces".
