### ISSUE TITLE
Error when loading factorio in 0.18.31 with this mod

### ISSUE THREAD

**Issue by LazyTurtle61** [jimmyjon711/FactorioExtended-Plus-Machines#19]
think its cuz of the new mining drill

**Comment by billbo99** [comment]
![image](https://user-images.githubusercontent.com/17733206/84281806-ebbc7d80-ab30-11ea-9ba9-5c5a24bacaff.png)
I will be submitting a pull request shortly for Jimmy

The schema for the electric miner was changed

**Comment by LazyTurtle61** [comment]
i guess its almost fixed by now?

**Comment by LazyTurtle61** [comment]
Would be nice by now haha

**Comment by jimmyjon711** [comment]
Fixed by pull request #20
