### ISSUE TITLE
Error when loading (version 0.4.4)

### ISSUE THREAD

**Issue by AndyMannnn** [jimmyjon711/FactorioExtended-Plus-Machines#23]
When loading factorio with the mod _FactorioExtended Plus-Machines_ active, there is an error with closing a file (idk what that means),
screenshot of loading error:
![Annotation 2020-06-17 140310](https://user-images.githubusercontent.com/67055581/84895893-5296e500-b0a3-11ea-8a13-862e9f6415c5.png)

**Comment by billbo99** [comment]
Have you tried deleting the ZIP file and downloading it again ?

Any chance your Anti-Virus programe is blocking access ?

Can you attach your "factorio-current.log" log file,  might be more info there

**Comment by AndyMannnn** [comment]
Tried deleting and installing the zip file, same issue.
Don't think its the anti-virus programe.
[factorio-current.log](https://github.com/jimmyjon711/FactorioExtended-Plus-Machines/files/4798113/factorio-current.log)

**Comment by LemonZawodowiec** [comment]
I came to up-vote this issue i have the same problem.

Failed to load mods: Closing file __FactorioExtended-Plus-Machines__/graphics/entity/centrifuge-mk3/centrifuge-A-mk3.png failed (-105): __FactorioExtended-Plus-Machines__/graphics/entity/centrifuge-mk3/centrifuge-A-mk3.png

[factorio-previous.log](https://github.com/jimmyjon711/FactorioExtended-Plus-Machines/files/4800931/factorio-previous.log)
I added my log from a crash launch maybe it can help somehow.

**Comment by LazyTurtle61** [comment]
the mod portal zip file is corrupted
as i reported :p

**Comment by LemonZawodowiec** [comment]
> the mod portal zip file is corrupted
> as i reported :p
---
@LazyTurtle61 thanks for writing. I downloaded the master version from here (Github) and all things (Factorio) launch fine.
You are my savior man, my own personal Jesus Christ.

**Comment by LazyTurtle61** [comment]
haha well thats good to hear

**Comment by jimmyjon711** [comment]
I re-uploaded the version, this should be fixed now
