### ISSUE TITLE
Mod not Loading

### ISSUE THREAD

**Issue by Grendowod** [jimmyjon711/FactorioExtended-Plus-Machines#27]
Hello

The mod, FactorioExtended-Plus-Machines, does not load in my version of Factorio.
I'm playing on Steam 1.0.0 and have loaded a mod or two. (all FactorioExtended and FactorioExtended-Plus and a few others)

However, FactorioExtended-Plus-Machines does not work since 0.4.4, 0.4.5 and 1.0.0. It's always the same mistake.
![FE+-Machien 1 0 0](https://user-images.githubusercontent.com/71136391/92932187-cf3c2400-f444-11ea-89bf-e5ac2cc745a5.png)

Can you have a look at it and give me some help. You're welcome.

Sorry for my english it's google translate my english is a thousand times worse.

MfG Grendowod

**Comment by Grendowod** [comment]
Hello

I have attached my Mod.List.json as a txt edited for a better overview.

The two marked do not work, the rest is loaded and runs on the current versions without crashing. Daily update of the mod database.

[mod-List.txt](https://github.com/jimmyjon711/FactorioExtended-Plus-Machines/files/5210987/mod-List.txt)

MfG Grendowod

**Comment by jimmyjon711** [comment]
Some other mods has to be conflicting with FactorioExtended-Plus mods. What happens if you disable the normal FactorioExtended mods?

**Comment by Grendowod** [comment]
Moin jimmyjon711

If all FactorioExtended mods are deactivated, the game starts with an error message.

I now deactivate one mod after the other until I find the mod cross-shooting.
![FehlermeldungFE+](https://user-images.githubusercontent.com/71136391/93016250-1dc1fd80-f5c0-11ea-8a46-32efca03038b.jpg)

**Comment by Grendowod** [comment]
Moin jimmyjon711

So I found the culprit.
It is. Drum roll: ScienceCostTweakerM_0.18.2.zip
For whatever reason.

I will currently deactivate it so that I can use your machines.

MfG Grendowod
