### ISSUE TITLE
Unable to update pump jack using 0.17 upgrade planner

### ISSUE THREAD

**Issue by Shadow-Logrus** [jimmyjon711/FactorioExtended-Plus-Machines#5]
Not sure if the problem with this mod, but I though I would try you first.

I built my first round of Pumpjack Mk2s, and was going to upgrade an oil patch. Using the upgrade planner in 0.17 I can get the pipes to upgrade, but the pumpjacks had to upgraded manually.

**Comment by jimmyjon711** [comment]
Thanks for reporting this, I will look into this and fix it soon

**Comment by jimmyjon711** [comment]
This should be updated in the latest release 0.2.2
