### ISSUE TITLE
Automation 4 is locked by Automation 2

### ISSUE THREAD

**Issue by MaxelDel** [jimmyjon711/FactorioExtended-Plus-Machines#8]
Automation 4 is locked by Automation 2 instead of Automation 3
That's the only reason FactorioExtended Plus-Machines Fix 0.17 still exists
https://mods.factorio.com/mod/FactorioExtended-Plus-Machines-Fix-17

**Comment by jimmyjon711** [comment]
FYI if you ever wanted to fix or add stuff in the future I will accept pull requests
